In [ ]:
"""
在读取数据时指定dtype
"""

In [1]:
import pandas as pd

In [10]:
import sys

In [2]:
dtype_dict = {
    "A": "float32",
    "B": "float32",
    "C": "float32",
    "D": "str",
    "E": "str",
    "F": "str"
}

In [7]:
pdf = pd.read_csv("demo_csv.csv", header=0, dtype=dtype_dict)

In [8]:
pdf

      A    B    C  D  E  F
0   1.0  2.0  3.0  e  q  u
1   2.0  3.0  4.0  a  b  g
2   5.0  6.0  7.0  m  r  g
3   7.0  8.0  9.0  n  f  t
4   1.0  2.0  3.0  e  q  u
5   2.0  3.0  4.0  a  b  g
6   5.0  6.0  7.0  m  r  g
7   7.0  8.0  9.0  n  f  t
8   1.0  2.0  3.0  e  q  u
9   2.0  3.0  4.0  a  b  g
10  5.0  6.0  7.0  m  r  g
11  7.0  8.0  9.0  n  f  t
12  1.0  2.0  3.0  e  q  u
13  2.0  3.0  4.0  a  b  g
14  5.0  6.0  7.0  m  r  g
15  7.0  8.0  9.0  n  f  t
16  1.0  2.0  3.0  e  q  u
17  2.0  3.0  4.0  a  b  g
18  5.0  6.0  7.0  m  r  g
19  7.0  8.0  9.0  n  f  t
20  1.0  2.0  3.0  e  q  u
21  2.0  3.0  4.0  a  b  g
22  5.0  6.0  7.0  m  r  g
23  7.0  8.0  9.0  n  f  t
24  1.0  2.0  3.0  e  q  u
25  2.0  3.0  4.0  a  b  g
26  5.0  6.0  7.0  m  r  g
27  7.0  8.0  9.0  n  f  t

In [9]:
pdf.dtypes

A    float32
B    float32
C    float32
D     object
E     object
F     object
dtype: object

In [11]:
sys.getsizeof(pdf)

6032

In [12]:
dtype_dict = {
    "A": "float64",
    "B": "float64",
    "C": "float64",
    "D": "str",
    "E": "str",
    "F": "str"
}

In [13]:
pdf = pd.read_csv("demo_csv.csv", header=0, dtype=dtype_dict)

In [14]:
pdf

      A    B    C  D  E  F
0   1.0  2.0  3.0  e  q  u
1   2.0  3.0  4.0  a  b  g
2   5.0  6.0  7.0  m  r  g
3   7.0  8.0  9.0  n  f  t
4   1.0  2.0  3.0  e  q  u
5   2.0  3.0  4.0  a  b  g
6   5.0  6.0  7.0  m  r  g
7   7.0  8.0  9.0  n  f  t
8   1.0  2.0  3.0  e  q  u
9   2.0  3.0  4.0  a  b  g
10  5.0  6.0  7.0  m  r  g
11  7.0  8.0  9.0  n  f  t
12  1.0  2.0  3.0  e  q  u
13  2.0  3.0  4.0  a  b  g
14  5.0  6.0  7.0  m  r  g
15  7.0  8.0  9.0  n  f  t
16  1.0  2.0  3.0  e  q  u
17  2.0  3.0  4.0  a  b  g
18  5.0  6.0  7.0  m  r  g
19  7.0  8.0  9.0  n  f  t
20  1.0  2.0  3.0  e  q  u
21  2.0  3.0  4.0  a  b  g
22  5.0  6.0  7.0  m  r  g
23  7.0  8.0  9.0  n  f  t
24  1.0  2.0  3.0  e  q  u
25  2.0  3.0  4.0  a  b  g
26  5.0  6.0  7.0  m  r  g
27  7.0  8.0  9.0  n  f  t

In [15]:
pdf.dtypes

A    float64
B    float64
C    float64
D     object
E     object
F     object
dtype: object

In [16]:
sys.getsizeof(pdf)

6368

In [17]:
dtype_dict = {
    "A": "float32",
    "B": "float32",
    "C": "float32",
}

In [18]:
pdf = pd.read_csv("demo_csv1.csv", header=0, dtype=dtype_dict)

In [19]:
pdf

      A    B    C
0   1.0  2.0  3.0
1   2.0  3.0  4.0
2   5.0  6.0  7.0
3   7.0  8.0  9.0
4   1.0  2.0  3.0
5   2.0  3.0  4.0
6   5.0  6.0  7.0
7   7.0  8.0  9.0
8   1.0  2.0  3.0
9   2.0  3.0  4.0
10  5.0  6.0  7.0
11  7.0  8.0  9.0
12  1.0  2.0  3.0
13  2.0  3.0  4.0
14  5.0  6.0  7.0
15  7.0  8.0  9.0
16  1.0  2.0  3.0
17  2.0  3.0  4.0
18  5.0  6.0  7.0
19  7.0  8.0  9.0
20  1.0  2.0  3.0
21  2.0  3.0  4.0
22  5.0  6.0  7.0
23  7.0  8.0  9.0

In [20]:
pdf.dtypes

A    float32
B    float32
C    float32
dtype: object

In [21]:
sys.getsizeof(pdf)

440

In [22]:
dtype_dict = {
    "A": "float64",
    "B": "float64",
    "C": "float64",
}

In [23]:
pdf = pd.read_csv("demo_csv1.csv", header=0, dtype=dtype_dict)

In [24]:
pdf

      A    B    C
0   1.0  2.0  3.0
1   2.0  3.0  4.0
2   5.0  6.0  7.0
3   7.0  8.0  9.0
4   1.0  2.0  3.0
5   2.0  3.0  4.0
6   5.0  6.0  7.0
7   7.0  8.0  9.0
8   1.0  2.0  3.0
9   2.0  3.0  4.0
10  5.0  6.0  7.0
11  7.0  8.0  9.0
12  1.0  2.0  3.0
13  2.0  3.0  4.0
14  5.0  6.0  7.0
15  7.0  8.0  9.0
16  1.0  2.0  3.0
17  2.0  3.0  4.0
18  5.0  6.0  7.0
19  7.0  8.0  9.0
20  1.0  2.0  3.0
21  2.0  3.0  4.0
22  5.0  6.0  7.0
23  7.0  8.0  9.0

In [25]:
pdf.dtypes

A    float64
B    float64
C    float64
dtype: object

In [26]:
sys.getsizeof(pdf)

728